--[[
* npcvalue
*
* Shows what an NPC shop pays for the item under your cursor in the game's item menus:
* inventory and the other bags, mog safe and storage, equipment lists, trade, delivery box,
* bazaar and shop selling. Drag the box where you want it while one of those menus is open.
*
* Prices come from data/prices.lua, generated by tools/gen_prices.py from LandSandBoat's item
* table (sql/item_basic.sql, BaseSell). A shop pays that price adjusted by your fame with the
* shop's area, 97.5% to 102.5% of it. Only items in your inventory can be sold, and some items
* no shop will buy.
*
* Nothing is ever sent to the server: npcvalue only reads client memory.
--]]

addon.name    = 'npcvalue';
addon.author  = 'Relli';
addon.version = '0.1';
addon.desc    = 'Shows what NPC shops pay for the item under your cursor.';
addon.link    = '';

require('common');
local chat     = require('chat');
local imgui    = require('imgui');
local settings = require('settings');

local defaults = T{
    visible = true,
    x = 60, y = 360,  -- where the price box sits
    debug = false,    -- show the game's menu name and selected item, even outside item menus
};

-- The game's item menus (names as stored in FFXiMain.dll), where the item you have highlighted
-- is the one the game tracks as selected. Item info windows (iteminfo, itemxinf, item4inf, ...)
-- and sort windows (itmsortw, ...) count too; see item_menu().
local ITEM_MENUS = {
    inventor = true,                                  -- inventory and the other bags
    iuse = true,                                      -- using an item
    bank = true, bankmenu = true,                     -- mog safe
    storage = true, storage2 = true, mnstorag = true, -- mog house storage
    armsort = true, wepsort = true,                   -- equipment lists
    trade = true, handover = true,                    -- trading with players and NPCs
    delivery = true,                                  -- delivery box
    bazaar = true,
    shopsell = true,
};

-- Bags in container order, for saying where the item is.
local BAGS = { [0] = 'inventory', 'Mog Safe', 'Storage', 'temporary items', 'Mog Locker', 'Mog Satchel', 'Mog Sack',
               'Mog Case', 'Mog Wardrobe', 'Mog Safe 2' };

local nv = {
    settings = nil,
    prices   = nil,    -- [item id] = gil, or false when shops won't buy it
    error    = nil,    -- why the price data didn't load
    moved    = false,  -- the box was dragged and its position should be saved
    reset    = false,  -- put the box back at its default position next frame
};

local function msg(text)
    print(chat.header(addon.name):append(chat.message(text)));
end

local function err(text)
    print(chat.header(addon.name):append(chat.error(text)));
end

local function load_prices()
    local f, why = loadfile(('%s\\data\\prices.lua'):fmt(addon.path));
    if (f == nil) then
        return nil, why;
    end
    local ok, t = pcall(f);
    if (not ok or type(t) ~= 'table') then
        return nil, ok and 'data/prices.lua did not return a table' or t;
    end
    return t;
end

--[[
* 1234567 -> '1,234,567'.
--]]
local function gil(n)
    local s = tostring(math.floor(n)):reverse():gsub('(%d%d%d)', '%1,'):reverse();
    return (s:gsub('^,', ''));
end

--[[
* The game's current menu name without its 'menu' prefix (e.g. 'inventor'), or ''.
* Read only; the same pointer path as HXUI's GetMenuName.
--]]
local menu_ptr = nil;
local function menu_name()
    if (menu_ptr == nil) then
        menu_ptr = ashita.memory.find('FFXiMain.dll', 0, '8B480C85C974??8B510885D274??3B05', 16, 0) or 0;
    end
    if (menu_ptr == 0) then
        return '';
    end
    local sub = ashita.memory.read_uint32(menu_ptr);
    if (sub == 0) then
        return '';
    end
    local value = ashita.memory.read_uint32(sub);
    if (value == 0) then
        return '';
    end
    local header = ashita.memory.read_uint32(value + 4);
    if (header == 0) then
        return '';
    end
    local name = ashita.memory.read_string(header + 0x46, 16):gsub('%z', '');
    return name:match('^menu%s+(%S+)') or '';
end

local function item_menu(name)
    return ITEM_MENUS[name] == true or name:match('^item') ~= nil or name:match('^itm') ~= nil;
end

--[[
* The highlighted item: { id, name, bag, count }; bag and count are nil when it isn't at the
* selected slot of any of your bags (a shop's or another player's item).
--]]
local function selected()
    local inv = AshitaCore:GetMemoryManager():GetInventory();
    local id, index = inv:GetSelectedItemId(), inv:GetSelectedItemIndex();
    if (id == nil or id == 0 or id == 0xFFFF) then
        return nil;
    end
    local res = AshitaCore:GetResourceManager():GetItemById(id);
    local name = res ~= nil and res.Name ~= nil and res.Name[1] or '';
    if (name == '') then
        name = inv:GetSelectedItemName() or '';
    end
    if (name == '') then
        name = ('Item %d'):fmt(id);
    end
    local it = { id = id, name = name };
    if (index ~= nil and index >= 0 and index <= 80) then
        for bag = 0, #BAGS do
            local item = inv:GetContainerItem(bag, index);
            if (item ~= nil and item.Id == id and item.Count > 0) then
                it.bag, it.count = bag, item.Count;
                break;
            end
        end
    end
    return it;
end

--[[
* The box's lines: { text, color } with colors as { r, g, b, a } floats.
--]]
local WHITE, GOLD, DIM, RED = { 0.95, 0.94, 0.91, 1 }, { 1.0, 0.82, 0.35, 1 }, { 0.67, 0.66, 0.63, 1 }, { 0.93, 0.45, 0.42, 1 };
local function lines(it)
    local out = { { it.name, WHITE } };
    local price = nv.prices and nv.prices[it.id];
    if (price == false) then
        out[#out + 1] = { 'NPCs won\'t buy this', RED };
    elseif (price == nil) then
        out[#out + 1] = { 'No NPC price known', DIM };
    elseif (price == 0) then
        out[#out + 1] = { 'NPCs pay nothing for this', DIM };
    elseif (it.count ~= nil and it.count > 1) then
        out[#out + 1] = { ('NPC pays %s each (x%d %s)'):fmt(gil(price), it.count, gil(price * it.count)), GOLD };
    else
        out[#out + 1] = { ('NPC pays %s'):fmt(gil(price)), GOLD };
    end
    if (price ~= nil and price ~= false and price > 0 and it.bag ~= nil and it.bag ~= 0) then
        out[#out + 1] = { ('In your %s: move it to your inventory to sell'):fmt(BAGS[it.bag]), DIM };
    end
    return out;
end

local function draw()
    local s = nv.settings;
    if (s == nil or not s.visible) then
        return;
    end
    local menu = menu_name();
    local show = { };
    if (item_menu(menu)) then
        local it = selected();
        if (it ~= nil) then
            show = lines(it);
        end
    end
    if (s.debug) then
        local inv = AshitaCore:GetMemoryManager():GetInventory();
        show[#show + 1] = { ('menu "%s"%s, selected %d at slot %d'):fmt(menu, item_menu(menu) and ' (item menu)' or '',
            inv:GetSelectedItemId() or 0, inv:GetSelectedItemIndex() or 0), DIM };
    end
    if (#show == 0) then
        return;
    end

    imgui.SetNextWindowPos({ s.x, s.y }, nv.reset and ImGuiCond_Always or ImGuiCond_FirstUseEver);
    nv.reset = false;
    imgui.PushStyleColor(ImGuiCol_WindowBg, { 0.09, 0.10, 0.12, 0.92 });
    imgui.PushStyleColor(ImGuiCol_Border, { 0.37, 0.37, 0.35, 0.8 });
    imgui.PushStyleVar(ImGuiStyleVar_WindowRounding, 6);
    imgui.PushStyleVar(ImGuiStyleVar_WindowPadding, { 10, 8 });
    local flags = bit.bor(ImGuiWindowFlags_NoTitleBar, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoFocusOnAppearing,
        ImGuiWindowFlags_NoNav, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoScrollbar);
    if (imgui.Begin('npcvalue', { true }, flags)) then
        for _, l in ipairs(show) do
            imgui.TextColored(l[2], l[1]);
        end
        local x, y = imgui.GetWindowPos();
        if (math.abs(x - s.x) > 0.5 or math.abs(y - s.y) > 0.5) then
            s.x, s.y, nv.moved = x, y, true;
        end
    end
    imgui.End();
    imgui.PopStyleVar(2);
    imgui.PopStyleColor(2);

    -- Save a new position once you let go of it.
    if (nv.moved and not imgui.IsMouseDown(ImGuiMouseButton_Left)) then
        nv.moved = false;
        settings.save();
    end
end

local function help()
    msg('/npcvalue (or /nv) on|off   show the price box in item menus');
    msg('/npcvalue reset   move the box back to where it starts (drag it to move it)');
    msg('/npcvalue debug   show the game\'s menu name and selected item, to report a menu the box misses');
    msg('Prices are before fame: shops pay 97.5% to 102.5% of them. Only inventory items can be sold.');
end

ashita.events.register('load', 'npcvalue_load', function ()
    nv.settings = settings.load(defaults);
    local prices, why = load_prices();
    nv.prices, nv.error = prices, why;
    if (prices == nil) then
        err(('No price data (%s). Run tools/gen_prices.py.'):fmt(tostring(why)));
    end
end);

settings.register('settings', 'npcvalue_settings_update', function (s)
    if (s ~= nil) then
        nv.settings = s;
    end
end);

ashita.events.register('unload', 'npcvalue_unload', function ()
    settings.save();
end);

ashita.events.register('command', 'npcvalue_command', function (e)
    local args = e.command:args();
    if (#args == 0 or (args[1]:lower() ~= '/npcvalue' and args[1]:lower() ~= '/nv')) then
        return;
    end
    e.blocked = true;
    local s = nv.settings;
    local what = (args[2] or ''):lower();
    if (what == 'on' or what == 'off') then
        s.visible = what == 'on';
        settings.save();
        msg(('Price box %s.'):fmt(s.visible and 'on' or 'off'));
    elseif (what == 'reset') then
        s.x, s.y, nv.reset = defaults.x, defaults.y, true;
        settings.save();
        msg('Price box moved back to where it starts.');
    elseif (what == 'debug') then
        s.debug = not s.debug;
        settings.save();
        msg(('Menu debug line %s.'):fmt(s.debug and 'on' or 'off'));
    else
        help();
    end
end);

ashita.events.register('d3d_present', 'npcvalue_present', function ()
    draw();
end);
