"""
Generates data/prices.lua for npcvalue from LandSandBoat's item table.

What an NPC shop pays for an item is its BaseSell in sql/item_basic.sql, adjusted by your fame
with the shop's area (xi.shop.onSellPriceCheck in scripts/globals/shop.lua): 97.5% to 102.5%,
at least 1 gil. Items with the NOSALE flag are refused by every shop.

    python tools/gen_prices.py [--lsb C:\\code\\LSB\\server] [--report]

The era module (modules/era) leaves sell prices alone; the script checks that no module changes
them and stops if one does, since the data would then be wrong for a server running it.
"""

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "data" / "prices.lua"

ROW = re.compile(
    r"^INSERT INTO `item_basic` VALUES \((\d+),(\d+),'([^']*)','[^']*','[^']*',([^,]+),(\d+),([^,]+),([^,]+),(\d+)\);",
    re.M)
# Anything in a module that would change what a shop pays.
PRICE_CHANGES = re.compile(r"BaseSell|onSellPriceCheck|setBasePrice|UPDATE\s+`?item_basic`?", re.I)


def read_items(lsb):
    text = (lsb / "sql" / "item_basic.sql").read_text(encoding="utf-8")
    rows = ROW.findall(text)
    inserts = text.count("INSERT INTO `item_basic`")
    if len(rows) != inserts:
        sys.exit("item_basic.sql: parsed %d of %d rows; the table layout changed" % (len(rows), inserts))
    items = {}
    for itemid, _sub, name, _type, _stack, flags, _ah, sell in rows:
        items[int(itemid)] = (name, int(sell), "@FLAG_NOSALE" in flags)
    return items


def module_price_changes(lsb):
    hits = []
    for p in sorted((lsb / "modules").rglob("*")):
        if p.suffix.lower() in (".lua", ".sql", ".txt", ".yaml") and p.is_file():
            for n, line in enumerate(p.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
                if PRICE_CHANGES.search(line):
                    hits.append("%s:%d: %s" % (p.relative_to(lsb), n, line.strip()))
    return hits


def write_lua(items, out):
    entries = []
    for itemid in sorted(items):
        _name, sell, nosale = items[itemid]
        entries.append("[%d]=%s" % (itemid, "false" if nosale else sell))
    lines = [
        "-- NPC sell prices for npcvalue, generated by tools/gen_prices.py from LandSandBoat's",
        "-- sql/item_basic.sql (BaseSell). Do not edit; run the script again instead.",
        "-- [item id] = gil a shop pays for one before fame (0 = nothing), or false when shops won't buy it.",
        "return {",
    ]
    for i in range(0, len(entries), 16):
        lines.append(",".join(entries[i:i + 16]) + ",")
    lines.append("}")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lsb", type=Path, default=Path(r"C:\code\LSB\server"), help="LandSandBoat server checkout")
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--report", action="store_true", help="print counts and a few sample prices")
    args = ap.parse_args(argv)

    hits = module_price_changes(args.lsb)
    if hits:
        print("These module lines may change sell prices; check them before trusting the data:")
        print("\n".join("  " + h for h in hits))
        return 1
    items = read_items(args.lsb)
    write_lua(items, args.out)
    priced = sum(1 for _, sell, nosale in items.values() if sell > 0 and not nosale)
    refused = sum(1 for _, _, nosale in items.values() if nosale)
    print("wrote %s: %d items, %d with a price, %d shops won't buy" % (args.out, len(items), priced, refused))
    if args.report:
        for itemid in (643, 827, 922, 4116, 1156):
            if itemid in items:
                print("  %5d %-24s %s" % (itemid, items[itemid][0], "won't buy" if items[itemid][2] else items[itemid][1]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
